apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k3k.fullname" . }}
  labels:
    {{- include "k3k.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.image.replicaCount }}
  selector:
     matchLabels:
      {{- include "k3k.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k3k.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          environment:
          - name: CLUSTER_CIDR
            value: {{ .Values.host.clusterCIDR }}
          ports:
          - containerPort: 8080
            name: https
            protocol: TCP
          - containerPort: 9443
            name: https-webhook
            protocol: TCP
      serviceAccountName: {{ include "k3k.serviceAccountName" . }}
