apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k3k.fullname" . }}
  labels:
    {{- include "k3k.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "k3k.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3k-node-proxy
rules:
- apiGroups:
  - ""
  resources:
  - "nodes"
  - "nodes/proxy"
  verbs:
  - "get"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k3k-node-proxy
roleRef:
  kind: ClusterRole
  name: k3k-node-proxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k3k-priorityclass
rules:
- apiGroups:
  - "scheduling.k8s.io"
  resources:
  - "priorityclasses"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k3k-priorityclass
roleRef:
  kind: ClusterRole
  name: k3k-priorityclass
  apiGroup: rbac.authorization.k8s.io
